# Generated by Django 4.2.13 on 2024-06-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_crimemodel_date_alter_crimemodel_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimemodel',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='crimemodel',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
    ]
